import {
  coy,
  coldarkDark,
  nightOwl,
  materialLight,
  materialDark,
  oneLight,
  oneDark,
  synthwave84,
  twilight,
  solarizedlight,
  coldarkCold,
  gruvboxDark,
  zTouch,
  xonokai,
  solarizedDarkAtom,
  prism,
  pojoaque,
  okaidia,
  nord,
  lucario,
  coyWithoutShadows,
  cb,
} from "react-syntax-highlighter/dist/esm/styles/prism";

import {
  ascetic,
  atelierDuneLight,
  atelierCaveDark,
  androidstudio,
  hopscotch,
} from "react-syntax-highlighter/dist/esm/styles/hljs";
export const themes: Record<string, any> = {
  coldarkDark,
  okaidia,
  nightOwl,
  materialDark,
  gruvboxDark,
  pojoaque,
  xonokai,
  cb,
  materialLight,
  oneLight,
  oneDark,
  synthwave84,
  coy,
  nord,
  solarizedlight,
  coldarkCold,
  zTouch,
  solarizedDarkAtom,
  prism,
  lucario,
  coyWithoutShadows,
  twilight,
  ascetic,
  atelierCaveDark,
  atelierDuneLight,
  androidstudio,
  hopscotch,
};
